version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    ports:
      - '6060:6060'
    networks:
      - db-network
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_NAME: db
      DB_USER: postgre
      DB_PASS: postgre

  image-host:
    build:
      context: ./
      dockerfile: ./image-host/Dockerfile
    depends_on:
      - db
    ports:
      - '3030:3030'
    networks:
      - db-network
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_NAME: db
      DB_USER: postgre
      DB_PASS: postgre

  frontend:
    build:
      context: frontend
      args:
        - VITE_BACKEND_HOST=http://localhost:6060
        - VITE_IMAGE_HOST=http://localhost:3030
    depends_on:
      - backend
      - image-host
    ports:
      - 80:80

  db:
    image: 'postgres:latest'
    ports:
      - '6300:5432'
    networks:
      - db-network
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: db
    volumes:
        - ./db/schema.sql://docker-entrypoint-initdb.d/schema.sql
        - db-data:/var/lib/postgresql/data

networks:
  db-network:

volumes:
    db-data:
